### ISSUE TITLE
As a guest, I should be able to browse public content / profiles

### ISSUE THREAD

**Issue by meganft** [rtravitz/pushpin#14]
As a guest user

When I visit '/'
I should see dropdown menu with options to select needed service
I should see option to Sign Up / Login
And I click on "Browse Professionals"
I should be on '/professionals'
I should see index of professionals.

**Comment by meganft** [comment]
The spec here specifically said "Browse public content / profiles," but we decided that our homepage would only have the search/dropdown bar, and everything else we made seemed to account for some kind of registered user. I am happy to add some things to this one, but couldn't decide for now so left super simple!

**Comment by meganft** [comment]
Updated to have 'browse' professionals

**Comment by AliSchlereth** [comment]
Style professionals by skill & prof profile
Remove phone and email add user image
