### ISSUE TITLE
As a registered user, I should be able to manage my account information

### ISSUE THREAD

**Issue by meganft** [rtravitz/pushpin#18]
As a registered user
When I visit '/users/:id'
And I click on a project under 'Projects with Proposals'
And I should be on '/proposals/:id'
And I click on 'Award this proposal to this professional'
I should be on  '/projects/:id'
I should see message history with professional
And I should see professional's information

**Comment by meganft** [comment]
Take this out for other story?

**Comment by alishersadikov** [comment]
moving this card back to backlog because I mistakenly thought this was about user updating their account info.
