### ISSUE TITLE
As a professional, I should be able to see all the work I've applied for.

### ISSUE THREAD

**Issue by rtravitz** [rtravitz/pushpin#23]
As a professional user
Who has applied for projects and is assigned to projects
When I am logged in
And I visit my dashboard
I should see the projects I have applied for
And the projects I am assigned to

**Comment by AliSchlereth** [comment]
-Working on making proposals on dashboard links to proposal shows

**Comment by meganft** [comment]
Proposals that have been assigned need to become "active projects" and no longer  a proposal on the dashboard
