### ISSUE TITLE
Requesters should be able to publicly post work they need done on their property. Part 2

### ISSUE THREAD

**Issue by AliSchlereth** [rtravitz/pushpin#9]
As a logged in user
When I visit /:username/project/:project_name
I should see a project's name
I should see a project's location
I should see a project's skill
I should see a project's description

**Comment by AliSchlereth** [comment]
Should the project  be publicly viewable?   As a guest?

**Comment by meganft** [comment]
Made decision to update the first line of this to 'requester' from guest - work being publicly available for the PushPin community but not to anyone
